[2023-03-16T09:45:29.278+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2023-03-16T09:45:29.295+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2023-03-16T09:45:29.296+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:45:29.296+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-16T09:45:29.296+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:45:29.319+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2023-03-15 00:00:00+00:00
[2023-03-16T09:45:29.330+0000] {standard_task_runner.py:55} INFO - Started process 102 to run task
[2023-03-16T09:45:29.337+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2023-03-15T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/p_download_upload.py', '--cfg-path', '/tmp/tmpaae8ln31']
[2023-03-16T09:45:29.340+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask download_dataset_task
[2023-03-16T09:45:29.361+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-16T09:45:29.397+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-16T09:45:29.450+0000] {task_command.py:388} INFO - Running <TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-15T00:00:00+00:00 [running]> on host 8d6d3f05a6c2
[2023-03-16T09:45:29.567+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-15T00:00:00+00:00
[2023-03-16T09:45:29.573+0000] {logging_mixin.py:137} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2023-03-16T09:45:29.576+0000] {logging_mixin.py:137} INFO - file path is /opt/***
[2023-03-16T09:45:29.576+0000] {p_download_upload.py:39} INFO - Downloading files...
[2023-03-16T09:46:58.130+0000] {p_download_upload.py:41} INFO - Downloading completed!
[2023-03-16T09:46:58.133+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-16T09:46:58.146+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230315T000000, start_date=20230316T094529, end_date=20230316T094658
[2023-03-16T09:46:58.174+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-16T09:46:58.203+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
