[2023-03-21T13:08:36.333+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [queued]>
[2023-03-21T13:08:36.406+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [queued]>
[2023-03-21T13:08:36.407+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:08:36.410+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 3
[2023-03-21T13:08:36.410+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:08:36.511+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocDeleteClusterOperator): delete_dataproc_cluster> on 2023-03-21 12:29:29.795825+00:00
[2023-03-21T13:08:36.541+0000] {standard_task_runner.py:55} INFO - Started process 36966 to run task
[2023-03-21T13:08:36.572+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'delete_dataproc_cluster', 'manual__2023-03-21T12:29:29.795825+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmp9ga4v7om']
[2023-03-21T13:08:36.585+0000] {standard_task_runner.py:83} INFO - Job 324: Subtask delete_dataproc_cluster
[2023-03-21T13:08:36.695+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T13:08:36.950+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.delete_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [running]> on host 796cac132c25
[2023-03-21T13:08:37.344+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=delete_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T12:29:29.795825+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T12:29:29.795825+00:00
[2023-03-21T13:08:37.355+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T13:08:37.356+0000] {dataproc.py:901} INFO - Deleting cluster: my-dataproc-cluster
[2023-03-21T13:09:08.735+0000] {dataproc.py:871} INFO - Cluster deleted.
[2023-03-21T13:09:08.778+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=delete_dataproc_cluster, execution_date=20230321T122929, start_date=20230321T130836, end_date=20230321T130908
[2023-03-21T13:09:08.878+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-21T13:09:08.927+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
