[2023-03-15T18:33:19.560+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2023-03-15T18:33:19.572+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-14T00:00:00+00:00 [queued]>
[2023-03-15T18:33:19.572+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T18:33:19.572+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-15T18:33:19.572+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T18:33:19.593+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2023-03-14 00:00:00+00:00
[2023-03-15T18:33:19.601+0000] {standard_task_runner.py:55} INFO - Started process 262 to run task
[2023-03-15T18:33:19.608+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2023-03-14T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/p_download_upload.py', '--cfg-path', '/tmp/tmp1oxazet7']
[2023-03-15T18:33:19.611+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask download_dataset_task
[2023-03-15T18:33:19.630+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-15T18:33:19.665+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-03-15T18:33:19.708+0000] {task_command.py:388} INFO - Running <TaskInstance: project_data_ingestion_gcs_dag.download_dataset_task scheduled__2023-03-14T00:00:00+00:00 [running]> on host 8d6d3f05a6c2
[2023-03-15T18:33:19.815+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-14T00:00:00+00:00
[2023-03-15T18:33:19.820+0000] {logging_mixin.py:137} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2023-03-15T18:33:19.822+0000] {logging_mixin.py:137} INFO - file path is /opt/***
[2023-03-15T18:33:19.823+0000] {p_download_upload.py:39} INFO - Downloading files...
[2023-03-15T18:34:33.685+0000] {p_download_upload.py:41} INFO - Downloading completed!
[2023-03-15T18:34:33.687+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-15T18:34:33.702+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230314T000000, start_date=20230315T183319, end_date=20230315T183433
[2023-03-15T18:34:33.953+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-15T18:34:33.982+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
