[2023-03-20T00:03:52.284+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:03:52.335+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:03:52.335+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:03:52.335+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-03-20T00:03:52.336+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:03:52.405+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): spark_processing> on 2023-03-20 00:00:42.861729+00:00
[2023-03-20T00:03:52.426+0000] {standard_task_runner.py:55} INFO - Started process 348 to run task
[2023-03-20T00:03:52.421+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_local_dag', 'spark_processing', 'manual__2023-03-20T00:00:42.861729+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/p_spark_local.py', '--cfg-path', '/tmp/tmpm85sn8ur']
[2023-03-20T00:03:52.434+0000] {standard_task_runner.py:83} INFO - Job 167: Subtask spark_processing
[2023-03-20T00:03:52.497+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T00:03:52.703+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [running]> on host 4fd00a82f4e9
[2023-03-20T00:03:52.947+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_local_dag
AIRFLOW_CTX_TASK_ID=spark_processing
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:42.861729+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T00:00:42.861729+00:00
[2023-03-20T00:03:52.952+0000] {logging_mixin.py:137} INFO - Creating Spark session
[2023-03-20T00:03:53.133+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/p_spark_local.py", line 19, in my_function
    .appName("bigquery-to-pyspark") \
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2023-03-20T00:03:53.179+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_local_dag, task_id=spark_processing, execution_date=20230320T000042, start_date=20230320T000352, end_date=20230320T000353
[2023-03-20T00:03:53.260+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 167 for task spark_processing (Java gateway process exited before sending its port number; 348)
[2023-03-20T00:03:53.328+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T00:03:53.460+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
