[2023-03-20T00:00:44.616+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:00:44.721+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:00:44.722+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:00:44.722+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-20T00:00:44.723+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:00:44.787+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): spark_processing> on 2023-03-20 00:00:42.861729+00:00
[2023-03-20T00:00:44.796+0000] {standard_task_runner.py:55} INFO - Started process 224 to run task
[2023-03-20T00:00:44.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_local_dag', 'spark_processing', 'manual__2023-03-20T00:00:42.861729+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/p_spark_local.py', '--cfg-path', '/tmp/tmp3qbb1xky']
[2023-03-20T00:00:44.844+0000] {standard_task_runner.py:83} INFO - Job 164: Subtask spark_processing
[2023-03-20T00:00:44.888+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T00:00:45.160+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [running]> on host 4fd00a82f4e9
[2023-03-20T00:00:45.684+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_local_dag
AIRFLOW_CTX_TASK_ID=spark_processing
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:42.861729+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T00:00:42.861729+00:00
[2023-03-20T00:00:45.685+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/p_spark_local.py", line 10, in my_function
    PROJECT_ID = os.environ.get("GCP_PROJECT_ID")
NameError: name 'os' is not defined
[2023-03-20T00:00:45.738+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_local_dag, task_id=spark_processing, execution_date=20230320T000042, start_date=20230320T000044, end_date=20230320T000045
[2023-03-20T00:00:45.876+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 164 for task spark_processing (name 'os' is not defined; 224)
[2023-03-20T00:00:45.926+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T00:00:46.116+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
