[2023-03-20T00:01:17.896+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:01:17.929+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [queued]>
[2023-03-20T00:01:17.929+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:01:17.930+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 3
[2023-03-20T00:01:17.930+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T00:01:18.002+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): spark_processing> on 2023-03-20 00:00:42.861729+00:00
[2023-03-20T00:01:18.019+0000] {standard_task_runner.py:55} INFO - Started process 245 to run task
[2023-03-20T00:01:18.035+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_local_dag', 'spark_processing', 'manual__2023-03-20T00:00:42.861729+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/p_spark_local.py', '--cfg-path', '/tmp/tmpb1m9jssw']
[2023-03-20T00:01:18.036+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask spark_processing
[2023-03-20T00:01:18.103+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-20T00:01:18.322+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_local_dag.spark_processing manual__2023-03-20T00:00:42.861729+00:00 [running]> on host 4fd00a82f4e9
[2023-03-20T00:01:18.826+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_local_dag
AIRFLOW_CTX_TASK_ID=spark_processing
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:42.861729+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-20T00:00:42.861729+00:00
[2023-03-20T00:01:19.347+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/p_spark_local.py", line 18, in my_function
    .appName('test') \
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2023-03-20T00:01:19.397+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_local_dag, task_id=spark_processing, execution_date=20230320T000042, start_date=20230320T000117, end_date=20230320T000119
[2023-03-20T00:01:19.507+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 165 for task spark_processing (Java gateway process exited before sending its port number; 245)
[2023-03-20T00:01:19.594+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T00:01:19.727+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
