[2023-03-21T14:03:15.461+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [queued]>
[2023-03-21T14:03:15.510+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [queued]>
[2023-03-21T14:03:15.511+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T14:03:15.511+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-21T14:03:15.512+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T14:03:15.572+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2023-03-21 14:00:00.595190+00:00
[2023-03-21T14:03:15.601+0000] {standard_task_runner.py:55} INFO - Started process 39390 to run task
[2023-03-21T14:03:15.632+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'create_dataproc_cluster', 'manual__2023-03-21T14:00:00.595190+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmpko4hugm3']
[2023-03-21T14:03:15.652+0000] {standard_task_runner.py:83} INFO - Job 343: Subtask create_dataproc_cluster
[2023-03-21T14:03:15.707+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T14:03:16.016+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T14:00:00.595190+00:00 [running]> on host 796cac132c25
[2023-03-21T14:03:16.455+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T14:00:00.595190+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T14:00:00.595190+00:00
[2023-03-21T14:03:16.458+0000] {dataproc.py:601} INFO - Creating cluster: my-dataproc-cluster
[2023-03-21T14:03:16.462+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T14:06:17.505+0000] {dataproc.py:614} INFO - Cluster created.
[2023-03-21T14:06:17.558+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=create_dataproc_cluster, execution_date=20230321T140000, start_date=20230321T140315, end_date=20230321T140617
[2023-03-21T14:06:17.627+0000] {local_task_job.py:212} INFO - Task exited with return code 0
