[2023-03-21T13:32:39.245+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [queued]>
[2023-03-21T13:32:39.260+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [queued]>
[2023-03-21T13:32:39.260+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:32:39.261+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-03-21T13:32:39.261+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T13:32:39.281+0000] {taskinstance.py:1303} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster> on 2023-03-21 12:29:29.795825+00:00
[2023-03-21T13:32:39.292+0000] {standard_task_runner.py:55} INFO - Started process 37975 to run task
[2023-03-21T13:32:39.300+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'project_masterdag', 'create_dataproc_cluster', 'manual__2023-03-21T12:29:29.795825+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/project_master_dags.py', '--cfg-path', '/tmp/tmp4rvgufwu']
[2023-03-21T13:32:39.303+0000] {standard_task_runner.py:83} INFO - Job 329: Subtask create_dataproc_cluster
[2023-03-21T13:32:39.327+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-21T13:32:39.412+0000] {task_command.py:388} INFO - Running <TaskInstance: project_masterdag.create_dataproc_cluster manual__2023-03-21T12:29:29.795825+00:00 [running]> on host 796cac132c25
[2023-03-21T13:32:39.526+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_masterdag
AIRFLOW_CTX_TASK_ID=create_dataproc_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T12:29:29.795825+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T12:29:29.795825+00:00
[2023-03-21T13:32:39.528+0000] {dataproc.py:601} INFO - Creating cluster: my-dataproc-cluster
[2023-03-21T13:32:39.530+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-03-21T13:35:30.867+0000] {dataproc.py:614} INFO - Cluster created.
[2023-03-21T13:35:30.933+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=project_masterdag, task_id=create_dataproc_cluster, execution_date=20230321T122929, start_date=20230321T133239, end_date=20230321T133530
[2023-03-21T13:35:30.993+0000] {local_task_job.py:212} INFO - Task exited with return code 0
